DROP TABLE T_GXP_LECTURE;
DROP TABLE T_GXP_EVENT_DAY;
DROP TABLE T_GXP_NOTIFICATION;
DROP TABLE T_GXP_ADMINISTRATOR_EVENT;
DROP TABLE T_GXP_VOTE;
DROP TABLE T_GXP_POLL_OPTION;
DROP TABLE T_GXP_POLL;
DROP TABLE T_GXP_PAYMENT;
DROP TABLE T_GXP_TICKET;
DROP TABLE T_GXP_TICKET_TYPE;
DROP TABLE T_GXP_COUPON;
DROP TABLE T_GXP_ADMINISTRATOR;
DROP TABLE T_GXP_SPEAKER;
DROP TABLE T_GXP_EVENT;
DROP TABLE T_GXP_USER;
DROP TABLE T_GXP_AUDIT;


CREATE TABLE T_GXP_USER (
    id_user INTEGER PRIMARY KEY,
    nm_user VARCHAR2(255) NOT NULL,
    ds_email VARCHAR2(100) NOT NULL UNIQUE,
    ds_password VARCHAR(150) NOT NULL,
    nr_cpf CHAR(11) NOT NULL UNIQUE,
    dt_birth DATE NOT NULL,
    url_avatar VARCHAR2(200) NOT NULL,
    tx_description CLOB,
    tx_interests CLOB
);

CREATE TABLE T_GXP_EVENT (
    id_event INTEGER PRIMARY KEY,
    nm_event VARCHAR2(150) NOT NULL,
    tx_description CLOB NOT NULL,
    ds_event_type VARCHAR2(70) CHECK (ds_event_type IN ('Online', 'Presencial', 'Híbrido')) NOT NULL,
    url_image VARCHAR2(200) NOT NULL
);

CREATE TABLE T_GXP_SPEAKER (
    id_speaker INTEGER PRIMARY KEY,
    nm_speaker VARCHAR2(100) NOT NULL,
    tx_description CLOB NOT NULL,
    url_social_media VARCHAR2(150) NOT NULL,
    ds_language VARCHAR2(70) NOT NULL,
    url_avatar VARCHAR2(200)
);

CREATE TABLE T_GXP_ADMINISTRATOR (
    id_administrator INTEGER PRIMARY KEY,
    ds_email VARCHAR2(100) NOT NULL UNIQUE,
    ds_password VARCHAR2(150) NOT NULL
);

CREATE TABLE T_GXP_COUPON (
    id_coupon INTEGER PRIMARY KEY,
    nm_coupon VARCHAR2(100) NOT NULL,
    tx_description CLOB NOT NULL,
    cod_coupon VARCHAR2(100) UNIQUE,
    vl_discount NUMBER(3,2) NOT NULL
);

CREATE TABLE T_GXP_TICKET_TYPE (
    id_ticket_type INTEGER PRIMARY KEY,
    vl_price NUMBER(6, 2) NOT NULL,
    ds_category VARCHAR2(70) NOT NULL,
    tx_description CLOB NOT NULL,
    nr_quantity INTEGER NOT NULL,
    nr_sold INTEGER DEFAULT 0 NOT NULL,
    dt_finished_at DATE,
    id_event INTEGER REFERENCES T_GXP_EVENT(id_event) NOT NULL
);

CREATE TABLE T_GXP_TICKET (
    id_ticket INTEGER PRIMARY KEY,
    dt_of_use DATE,
    dt_issued DATE NOT NULL,
    nr_ticket VARCHAR2(100) NOT NULL UNIQUE,
    id_user INTEGER REFERENCES T_GXP_USER(id_user) NOT NULL,
    id_ticket_type INTEGER REFERENCES T_GXP_TICKET_TYPE(id_ticket_type) NOT NULL,
    id_coupon INTEGER REFERENCES T_GXP_COUPON(id_coupon)
);

CREATE TABLE T_GXP_PAYMENT (
    id_payment INTEGER PRIMARY KEY,
    ds_payment_method VARCHAR2(100) CHECK(ds_payment_method IN ('Cartão de Crédito', 'Cartão de Débito', 'Pix', 'Boleto')) NOT NULL,
    st_payment VARCHAR2(70) CHECK(st_payment IN ('Pendente', 'Aprovado', 'Concluído', 'Cancelado')) NOT NULL,
    vl_total_price NUMBER(6, 2) NOT NULL,
    dt_due DATE NOT NULL,
    dt_payment DATE,
    id_ticket INTEGER REFERENCES T_GXP_TICKET(id_ticket) NOT NULL
);

CREATE TABLE T_GXP_POLL (
    id_poll INTEGER PRIMARY KEY,
    nm_poll VARCHAR2(150) NOT NULL,
    dt_created_at DATE DEFAULT SYSTIMESTAMP NOT NULL,
    id_event INTEGER REFERENCES T_GXP_EVENT(id_event) NOT NULL
);

CREATE TABLE T_GXP_POLL_OPTION (
    id_poll_option INTEGER PRIMARY KEY,
    tx_description CLOB NOT NULL,
    nr_votes INTEGER DEFAULT 0 NOT NULL,
    id_poll INTEGER REFERENCES T_GXP_POLL(id_poll) NOT NULL
);

CREATE TABLE T_GXP_VOTE (
    id_vote INTEGER PRIMARY KEY,
    dt_created_at DATE DEFAULT SYSTIMESTAMP NOT NULL,
    id_poll_option INTEGER REFERENCES T_GXP_POLL_OPTION(id_poll_option) NOT NULL,
    id_user INTEGER REFERENCES T_GXP_USER(id_user) NOT NULL
);

CREATE TABLE T_GXP_ADMINISTRATOR_EVENT (
    id_administrator_event INTEGER PRIMARY KEY,
    id_administrator INTEGER REFERENCES T_GXP_ADMINISTRATOR(id_administrator) NOT NULL,
    id_event INTEGER REFERENCES T_GXP_EVENT(id_event) NOT NULL
);

CREATE TABLE T_GXP_NOTIFICATION (
    id_notification INTEGER PRIMARY KEY,
    dt_notification DATE NOT NULL,
    ds_notification_type VARCHAR2(70) NOT NULL,
    tx_content CLOB NOT NULL,
    id_event INTEGER REFERENCES T_GXP_EVENT(id_event) NOT NULL
);

CREATE TABLE T_GXP_EVENT_DAY(
    id_event_day INTEGER PRIMARY KEY,
    dt_start DATE NOT NULL,
    dt_end DATE NOT NULL,
    url_transmission VARCHAR2(100),
    id_event INTEGER REFERENCES T_GXP_EVENT(id_event) NOT NULL
);

CREATE TABLE T_GXP_LECTURE (
    id_lecture INTEGER PRIMARY KEY,
    nm_lecture VARCHAR2(150) NOT NULL,
    tx_description CLOB NOT NULL,
    dt_lecture DATE NOT NULL,
    id_event_day INTEGER REFERENCES T_GXP_EVENT_DAY(id_event_day) NOT NULL,
    id_speaker INTEGER REFERENCES T_GXP_SPEAKER(id_speaker) NOT NULL
);

CREATE TABLE T_GXP_AUDIT(
    id_audit INTEGER PRIMARY KEY,
    old_nm_event VARCHAR2(150),
    old_tx_description CLOB,
    old_ds_event_type VARCHAR2(70),
    old_url_image VARCHAR2(200),
    new_nm_event VARCHAR2(150),
    new_tx_description CLOB,
    new_ds_event_type VARCHAR2(70),
    new_url_image VARCHAR2(200),
    nm_author VARCHAR2(255) NOT NULL,
    dt_operation TIMESTAMP DEFAULT SYSDATE NOT NULL,
    ds_operation VARCHAR2(70) CHECK(ds_operation IN ('INSERT', 'UPDATE', 'DELETE')) NOT NULL
);

CREATE SEQUENCE SEQ_T_GXP_USER START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_EVENT START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_SPEAKER START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_ADMINISTRATOR START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_COUPON START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_TICKET_TYPE START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_TICKET START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_PAYMENT START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_POLL START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_POLL_OPTION START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_VOTE START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_ADMINISTRATOR_EVENT START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_NOTIFICATION START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_EVENT_DAY START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_LECTURE START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;
CREATE SEQUENCE SEQ_T_GXP_AUDIT START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCYCLE;

DROP SEQUENCE SEQ_T_GXP_USER;
DROP SEQUENCE SEQ_T_GXP_EVENT;
DROP SEQUENCE SEQ_T_GXP_SPEAKER;
DROP SEQUENCE SEQ_T_GXP_ADMINISTRATOR;
DROP SEQUENCE SEQ_T_GXP_COUPON;
DROP SEQUENCE SEQ_T_GXP_TICKET_TYPE;
DROP SEQUENCE SEQ_T_GXP_TICKET;
DROP SEQUENCE SEQ_T_GXP_PAYMENT;
DROP SEQUENCE SEQ_T_GXP_POLL;
DROP SEQUENCE SEQ_T_GXP_POLL_OPTION;
DROP SEQUENCE SEQ_T_GXP_VOTE;
DROP SEQUENCE SEQ_T_GXP_ADMINISTRATOR_EVENT;
DROP SEQUENCE SEQ_T_GXP_NOTIFICATION;
DROP SEQUENCE SEQ_T_GXP_EVENT_DAY;
DROP SEQUENCE SEQ_T_GXP_LECTURE;
DROP SEQUENCE SEQ_T_GXP_AUDIT;
